# Generated by Django 5.0.4 on 2024-05-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARZapp', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('adminid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
