# Generated by Django 5.0.4 on 2024-05-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARZapp', '0004_adminlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
